#!/bin/bash
#
# Auto-generate email-name-map.txt by:
# 1. Scanning upcoming calendar meetings for attendee emails
# 2. Scanning vault for person folders
# 3. Matching emails to folder names
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAP_FILE="${SCRIPT_DIR}/email-name-map.txt"
VAULT_PATH="$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents/U"

echo "🔍 Generating email-to-name mapping..."

# Step 1: Get all unique emails from upcoming meetings
echo "📅 Scanning upcoming meetings (next 30 days)..."
MEETING_EMAILS=$(khal list now 30d --format "{attendees}" 2>/dev/null | \
    tr ',' '\n' | \
    tr ' ' '\n' | \
    grep '@' | \
    sort -u)

UNIQUE_EMAIL_COUNT=$(echo "$MEETING_EMAILS" | wc -l | xargs)
echo "   Found $UNIQUE_EMAIL_COUNT unique email addresses"

# Step 2: Scan vault for person folders
echo "👥 Scanning vault for person folders..."
PERSON_FOLDERS=()

# Scan IPMedia
if [[ -d "$VAULT_PATH/Business/People/IPMedia" ]]; then
    while IFS= read -r folder; do
        folder_name=$(basename "$folder")
        # Skip hidden files and Teams folder
        [[ "$folder_name" =~ ^\. ]] && continue
        [[ "$folder_name" == "Teams" ]] && continue
        [[ "$folder_name" == "Inactive" ]] && continue
        PERSON_FOLDERS+=("$folder_name")
    done < <(find "$VAULT_PATH/Business/People/IPMedia" -maxdepth 1 -type d)
fi

echo "   Found ${#PERSON_FOLDERS[@]} person folders"

# Step 3: Create mapping file
echo "🔗 Creating mappings..."

cat > "$MAP_FILE" << 'HEADER'
# Email to Obsidian Name Mapping
# Format: email=FolderName
# Auto-generated by generate-email-map.sh
# Last updated: $(date +%Y-%m-%d)

# Skip self
jeff@ipmedia.com.br=SKIP
jeff.hamersly@gmail.com=SKIP
jeff@meupatrocinio.com=SKIP

# Auto-mapped from calendar + vault
HEADER

MAPPED_COUNT=0
UNMAPPED_EMAILS=()

while IFS= read -r email; do
    [[ -z "$email" ]] && continue

    # Skip Jeff's emails
    if [[ "$email" =~ jeff ]]; then
        continue
    fi

    # Extract name from email (before @)
    local_part="${email%%@*}"

    # Try to match with person folders
    FOUND=false

    # Strategy 1: firstname.lastname@domain → Firstname
    if [[ "$local_part" =~ \. ]]; then
        first_name="${local_part%%.*}"
        first_name_cap="$(tr '[:lower:]' '[:upper:]' <<< ${first_name:0:1})${first_name:1}"

        # Check if folder exists with this name
        for folder in "${PERSON_FOLDERS[@]}"; do
            if [[ "$folder" == "$first_name_cap" ]]; then
                echo "$email=$folder" >> "$MAP_FILE"
                ((MAPPED_COUNT++))
                FOUND=true
                break
            fi
        done
    fi

    # Strategy 2: Check for special cases (Otávio, etc.)
    if [[ ! "$FOUND" == true ]]; then
        for folder in "${PERSON_FOLDERS[@]}"; do
            folder_lower=$(echo "$folder" | tr '[:upper:]' '[:lower:]')
            folder_ascii=$(echo "$folder_lower" | iconv -f UTF-8 -t ASCII//TRANSLIT 2>/dev/null)

            if [[ "$local_part" =~ $folder_ascii ]] || [[ "$local_part" =~ $folder_lower ]]; then
                echo "$email=$folder" >> "$MAP_FILE"
                ((MAPPED_COUNT++))
                FOUND=true
                break
            fi
        done
    fi

    if [[ ! "$FOUND" == true ]]; then
        UNMAPPED_EMAILS+=("$email")
    fi

done <<< "$MEETING_EMAILS"

echo ""
echo "✅ Mapping complete!"
echo "   📊 Mapped: $MAPPED_COUNT emails"
echo "   ❓ Unmapped: ${#UNMAPPED_EMAILS[@]} emails"

if [[ ${#UNMAPPED_EMAILS[@]} -gt 0 ]]; then
    echo ""
    echo "⚠️  Unmapped emails (add to vault or manually map):"
    for email in "${UNMAPPED_EMAILS[@]}"; do
        echo "   - $email"
    done

    echo ""
    echo "# Unmapped emails - add manually" >> "$MAP_FILE"
    for email in "${UNMAPPED_EMAILS[@]}"; do
        # Suggest a name based on email
        local_part="${email%%@*}"
        suggested_name="$(tr '[:lower:]' '[:upper:]' <<< ${local_part:0:1})${local_part:1}"
        echo "# $email=$suggested_name" >> "$MAP_FILE"
    done
fi

echo ""
echo "📄 Mapping file: $MAP_FILE"
echo "   Total entries: $(grep -v '^#' "$MAP_FILE" | grep '=' | wc -l | xargs)"
